export const FIRST_CHAT = 'FIRST_CHAT';
export const NEW_CHAT = 'NEW_CHAT';
export const MSG_ARR = 'MSG_ARR';
export const KEY = 'KEY';
export const MESSAGE = 'MESSAGE';
export const USER_DATA = 'USER_DATA';
export const CHAT_USER = 'CHAT_USER';
export const ALL_USERS = 'ALL_USERS';
export const USERS_SEARCH = 'USERS_SEARCH';
export const IS_TYPING = 'IS_TYPING';
export const IS_GROUP = 'IS_GROUP';
export const GROUP_USER = 'GROUP_USER';
export const GROUP_NAME = 'GROUP_NAME';
export const GROUP_IMG = 'GROUP_IMG';
export const SHOW_MODAL='SHOW_MODAL'
